M48
; DRILL file {KiCad 7.0.9} date Tue Nov 28 01:14:29 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-28T01:14:29-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.270
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X182.96Y-69.0
X182.96Y-81.0
X182.96Y-85.0
X182.96Y-97.0
X182.96Y-101.0
X182.96Y-113.0
T2
X150.0Y-70.0
X150.0Y-112.0
T0
M30
